## The id of the VPC where Arena will be deployed. Mandatory.
vpcId: vpc-09989c3f6c3f13d89
availabilityZone: us-east-1a
privateSubnetId: subnet-04256bea30e540f20
# Instance type for Control Node
controlNodeInstanceType: "t2.large"
# Control Node whitelisted IPs
controlNodeWhitelist: 
  - '192.168.0.0/16' # Warning: this mean that access is open to the internet 
vpcCIDR: '10.218.0.0/24'
# Where to install
#env:
#  region: '<region>'
#  account: '<account_no>'