## The id of the VPC where Arena will be deployed. Mandatory.
vpcId: vpc-0c5f937bd3de67ea0
availabilityZone: us-east-1a
privateSubnetId: subnet-025c61f2aab4b5c59
# Instance type for Control Node
controlNodeInstanceType: "t2.large"

# Control Node whitelisted IPs
controlNodeWhitelist: 
  - '0.0.0.0/0' # Warning: this mean that access is open to the internet 

# Where to install
#env:
#  region: '<region>'
#  account: '<account_no>'