## The id of the VPC where Arena will be deployed. Mandatory.
vpcId: #######
availabilityZone: #######
privateSubnetId: #######
# Instance type for Control Node
controlNodeInstanceType: "t2.large"
# Control Node whitelisted IPs
controlNodeWhitelist: 
  - '192.168.0.0/16' # Warning: this mean that access is open to the internet 
vpcCIDR: '10.218.0.0/24'
# Where to install
#env:
#  region: '<region>'
#  account: '<account_no>'